server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: sport-service
          uri: lb://sport-service
          predicates:
            - Path=/sport-service/**
          filters:
            - RewritePath=/sport-service/(?<segment>.*),/$\{segment}

        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/mail-service/**
          filters:
            - RewritePath=/mail-service/(?<segment>.*),/$\{segment}